### ISSUE TITLE
Tests fail for sample xml files

### ISSUE THREAD

**Issue by temetski** [ggomes/otm-tools#1]
Running tests.m only works on line.xml (using the sample test_configs found in [otm-base](http://github.com/ggomes/otm-base).)
A sample error for onramp_offramp.xml is 
```
Error using OTM/run_simple (line 169)
Java exception occurred:
java.lang.NullPointerException
	at common.AbstractLaneGroup.add_state(AbstractLaneGroup.java:217)
	at common.AbstractLinkModel.register_commodity(AbstractLinkModel.java:48)
	at commodity.Commodity.initialize(Commodity.java:102)
	at runner.Scenario.initialize(Scenario.java:124)
	at runner.OTM.initialize(OTM.java:188)
	at runner.OTM.run(OTM.java:166)
	at runner.OTM.run(OTM.java:162)
	at api.API.run(API.java:655)
	at api.API.run(API.java:671)
```

**Comment by temetski** [comment]
Looks like my `javaclasspath.txt` was pointing to a stale version of otm-sim.
